# Exploración de datos
Análisis histológico via análisis elemental por microfluorescencia de rayos X.

## Imports

In [1]:
import numpy as np
import os
from sklearn.utils import Bunch
import pandas as pd

from load_dataset import load_fluorescence

## Creating the Dataset

### Dataset Validation

In [2]:
# We use our function imported from the module
directory = 'data'
dataset = load_fluorescence(directory)

In [3]:
dataset.DESCR

"Fluorescence Dataset\n\n    ADD EXPERIMENTAL METHODOLOGY HERE.\n\n    This dataset contains fluorescence images for elemental composition\n    analysis of mammary gland adenocarcinomas in mice. It contains various\n    mouse samples, each of which have been measured at least one. Different\n    measurements of the same mouse are indexed by the 'take' attribute. Each\n    mouse has also had a specific diet. The dataset is structured as follows:\n\n    - DESCR: A string description of the dataset.\n    - diet: A 1D array where each element is an integer\n        (0: 'control', 1: 'omega3', 2: 'omega6') indicating the diet category\n        for each sample.\n    - diet_names: A list of strings with the diet names:\n        ['control', 'omega3', 'omega6'], where the index of each element\n        coincides with its mapping value.\n    - mouse: A 1D array containing the mouse number for each sample.\n    - take: A 1D array containing the take number for each sample.\n    - images: A list o

In [4]:
dataset.diet

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
dataset.diet_names

['control', 'omega3', 'omega6']

In [6]:
dataset.mouse

array([31, 37, 29, 30, 33, 38, 32, 35, 36, 28, 27, 39,  8,  9,  6, 12,  7,
        1,  4,  1, 12, 10,  2, 11, 10, 14, 25, 18, 17, 21, 20, 23, 16, 26,
       25, 15, 19])

In [7]:
dataset.take

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [8]:
dataset.element_order

['Ca', 'Cu', 'Fe', 'K', 'Mn', 'P', 'S', 'Zn']

In [9]:
dataset.images

[array([[[4.99613e+08, 5.84112e+07, 1.24686e+09, ..., 0.00000e+00,
          0.00000e+00, 6.07647e+07],
         [5.23519e+08, 0.00000e+00, 5.12422e+09, ..., 0.00000e+00,
          1.94452e+07, 1.49408e+07],
         [6.50201e+08, 2.17309e+05, 6.71875e+08, ..., 0.00000e+00,
          0.00000e+00, 2.88480e+07],
         ...,
         [7.15644e+08, 0.00000e+00, 1.28831e+08, ..., 0.00000e+00,
          0.00000e+00, 1.44193e+07],
         [6.21493e+08, 1.27993e+07, 1.45191e+08, ..., 0.00000e+00,
          0.00000e+00, 3.83748e+07],
         [4.19220e+08, 1.14023e+07, 1.29464e+08, ..., 0.00000e+00,
          0.00000e+00, 2.87885e+07]],
 
        [[7.03493e+08, 5.56291e+07, 1.28770e+09, ..., 0.00000e+00,
          0.00000e+00, 7.61040e+07],
         [7.37935e+08, 0.00000e+00, 2.71789e+09, ..., 0.00000e+00,
          0.00000e+00, 3.04536e+07],
         [8.10767e+08, 9.67050e+06, 5.51022e+08, ..., 0.00000e+00,
          0.00000e+00, 3.09839e+07],
         ...,
         [8.18042e+08, 8.98752e+0

In [10]:
len(dataset.take)

37

In [11]:
len(dataset.mouse)

37

In [12]:
len(dataset.diet)

37

In [13]:
len(dataset.images)

37

In [14]:
len(dataset.images)*8

296

In [15]:
for image in dataset.images:
    print(image.shape)

(46, 51, 8)
(51, 51, 8)
(51, 51, 8)
(51, 51, 8)
(51, 51, 8)
(41, 41, 8)
(51, 51, 8)
(51, 51, 8)
(87, 31, 8)
(118, 121, 8)
(51, 51, 8)
(101, 101, 8)
(51, 51, 8)
(51, 51, 8)
(101, 101, 8)
(51, 51, 8)
(101, 101, 8)
(51, 51, 8)
(101, 101, 8)
(48, 68, 8)
(51, 51, 8)
(101, 101, 8)
(101, 101, 8)
(51, 51, 8)
(51, 51, 8)
(101, 101, 8)
(51, 51, 8)
(61, 61, 8)
(82, 81, 8)
(51, 26, 8)
(21, 21, 8)
(93, 81, 8)
(51, 51, 8)
(51, 51, 8)
(51, 51, 8)
(101, 101, 8)
(51, 56, 8)


In [16]:
t = pd.Series(dataset.take, dtype='str')
m = pd.Series(dataset.mouse, dtype='str')

# dataframe with m and t as columns
df = pd.DataFrame(data=m, columns=['mouse'])
df['take'] = t
df['mouse_take'] = df['mouse'] + df['take']
print(f'number of cases: {len(df['mouse_take'].unique())}')
df['mouse_take'].unique()

number of cases: 37


array(['310', '370', '290', '300', '330', '380', '320', '350', '360',
       '280', '270', '390', '80', '90', '60', '121', '70', '10', '40',
       '11', '120', '101', '20', '110', '100', '140', '250', '180', '170',
       '210', '200', '230', '160', '260', '251', '150', '190'],
      dtype=object)

In [17]:
# # Function to extract metadata from the filename
# def extract_metadata(filename):
#     """Extract metadata from file name

#     Note: names are of the form 
#     'dieta_control_raton_1_toma_0_element_Ca.dat'

#     """
#     parts = filename.split('_')
#     diet = parts[1]
#     raton = int(parts[3])
#     toma = int(parts[5])
#     elem = parts[7].replace('.dat', '')
#     return diet, raton, toma, elem


This is much better. However, I'd like to simplify the structure a bit more. First, some name changes. Use element_order in lower case. I'd also like to use 'mouse' instead of 'raton', 'take' instead of 'toma' and load_fluorescence instead of create_dataset (I'm trying to mimic the way scikit learn handles datasets). load_fluorescence should return a Bunch object with the following attributes:
- DESCR, a string with a description of the dataset, just leave it as an empty string for now.
- diet, a one-dimensional numpy array that contains integers corresponding to the mapping: {0 : 'control', 1 : 'omega3', 2 : 'omega6'}
- diet_names, a list of strings with the diet names for each number, i.e., ['control', 'omega3', 'omega6']
- mouse, a one-dimensional numpy array that contains integers corresponding to the raton number
- take, a one-dimensional numpy array that contains integers corresponding to the toma number
- images, a four-dimensional numpy array that contains the 3D images for each diet, mouse, and take. E.g., images[n] contains the three-dimensional np.array that corresponds to diet[n], mouse[n], and take[n]. The three dimensional images should be the agregation of the 2D images in the order specified by element_order. That is, images[n][0] is the 2D image for the fluorescence of Ca, of mouse[n], take[n] with diet[n].
- element_order, a list of strings with the names of the element in the order used to build the 3D images for each mouse, take, and diet, i.e., ['Ca', 'Cu', 'Fe', 'K', 'Mn', 'P', 'S', 'Zn'].

In [18]:
print(dataset.DESCR)

Fluorescence Dataset

    ADD EXPERIMENTAL METHODOLOGY HERE.

    This dataset contains fluorescence images for elemental composition
    analysis of mammary gland adenocarcinomas in mice. It contains various
    mouse samples, each of which have been measured at least one. Different
    measurements of the same mouse are indexed by the 'take' attribute. Each
    mouse has also had a specific diet. The dataset is structured as follows:

    - DESCR: A string description of the dataset.
    - diet: A 1D array where each element is an integer
        (0: 'control', 1: 'omega3', 2: 'omega6') indicating the diet category
        for each sample.
    - diet_names: A list of strings with the diet names:
        ['control', 'omega3', 'omega6'], where the index of each element
        coincides with its mapping value.
    - mouse: A 1D array containing the mouse number for each sample.
    - take: A 1D array containing the take number for each sample.
    - images: A list of 3D NumPy arrays re